experiment_name: cifar_ae

datasets:
  train: iin.data.CIFAR10Train
  validation: iin.data.CIFAR10Test

fid:
  batch_size: 50
fid_stats:
  pre_calc_stat_path: "fid_stats/cifar.npz"

model: iin.models.ae.Model
Model:
  deterministic: false
  in_channels: 3
  in_size: 32
  n_down: 4
  norm: an
  z_dim: 64

loss: iin.losses.ae.LossPND
Loss:
  calibrate: true
  disc_in_channels: 3
  disc_start: 100001
  logvar_init: 0.0
  perceptual_weight: 1.0
  d_lr_factor: 4.0
  spectral_norm: True

iterator: iin.iterators.ae.Trainer
base_learning_rate: 4.5e-06
batch_size: 25
log_freq: 1000
num_epochs: 300
decay_start: 505001
